---
apiVersion: v1
kind: Service
metadata:
  name: drupal-mysql-service
spec:
  ports: 
    -
      name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
      type: ClusterIP
  selector:
    app: drupal-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-mysql
  spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drupal-mysql
    spec:
      containers:
        -
          env:

            - name:  MYSQL_HOST
              value: drupal-db-test.cp9p94zrg0us.ap-southeast-1.rds.amazonaws.com
            - name:  MYSQL_USER
              value: admin
            - name: MYSQL_PASSWORD
              value: rafli001
            - name: MYSQL_DATABASE
              value: drupaldb

          image: "mysql"
          name: cont-drupal-mysql
          ports:
            -
              containerPort: 3306
              name: mysql
              protocol: TCP
          volumeMounts:
            -
              mountPath: /var/lib/mysql
              name: vol-drupal
              subPath: dbdata
      volumes:
        -
          name: vol-drupal
          persistentVolumeClaim:
            claimName: drupal-pvc-mysql