apiVersion: v1
kind: Secret
metadata:
  name: pesbuk-secret-cloud
type: Opaque
data:
  # DB_HOST: c3RhZ2dpbmcuY3A5cDk0enJnMHVzLmFwLXNvdXRoZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
  DB_USER: ZGV2b3BzY2lsc3k=
  DB_PASS: MTIzNDU2Nzg5MA==
  # password: {{ .Values.password | b64enc }}